Repository GlobalX/PockyBot.NET, pull requests merged in 2022-06, with the labels that each got.

#117 fix(username updater): suppress user not found errors in username updater
  src/PockyBot.NET.Tests/Services/DirectResultsMessageSenderTests.cs
  src/PockyBot.NET.Tests/Services/UsernameUpdaterTests.cs
  src/PockyBot.NET/PockyBotFactory.cs
  src/PockyBot.NET/Services/DirectResultsMessageSender.cs
  src/PockyBot.NET/Services/UsernameUpdater.cs
Labels: bug

#201 fix username updater 2
  src/PockyBot.NET/Services/UsernameUpdater.cs
Labels: bug

#203 Update peg check order
  src/PockyBot.NET.Tests/Services/Pegs/PegHelperTests.cs
  src/PockyBot.NET.Tests/Services/Pegs/PegRequestValidatorTests.cs
  src/PockyBot.NET.Tests/Services/Pegs/PegResultsHelperTests.cs
  src/PockyBot.NET.Tests/Services/Triggers/PegTests.cs
  src/PockyBot.NET.Tests/TestData/Pegs/PegRequestValidatorTestData.cs
  src/PockyBot.NET.Tests/TestData/Triggers/PegTestData.cs
  src/PockyBot.NET/Services/Pegs/IPegHelper.cs
  src/PockyBot.NET/Services/Pegs/IPegRequestValidator.cs
  src/PockyBot.NET/Services/Pegs/PegHelper.cs
  src/PockyBot.NET/Services/Pegs/PegRequestValidator.cs
  src/PockyBot.NET/Services/Pegs/PegResultsHelper.cs
  src/PockyBot.NET/Services/Triggers/Peg.cs
  src/PockyBot.NET/Services/Triggers/Status.cs
Labels: bug, enhancement

#205 Bugfix/codacy
  README.md
  cover.sh
Labels: bug

#207 chore: update travis ci badge
  README.md
Labels: documentation

#208 Bugfix/newlines
  src/PockyBot.NET/Resources/results.html
  src/PockyBot.NET/Services/Triggers/Status.cs
Labels: bug
